# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Imaging Systems Lab
first_name: Edmund Y. 
last_name: Lam
email: elam@eee.hku.hk
description: > # this means to ignore newlines until "baseurl:"
baseurl: 
url: https://isl-hku.github.io
last_updated: true # set to true if you want to display last updated in the footer
future : true

footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> and <a href="https://github.com/inukshuk/jekyll-scholar" target="_blank">Jekyll Scholar</a>
navbar_fixed: true
footer_fixed: false

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

exclude:
  - script


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Post  # your blog must have a name for it to show up in the nav bar
blog_description:
permalink: /blog/:year/:title/

# disqus:
#   identifier: "neysachen"

markdown: kramdown # to show TOC
# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: true
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


toc:
  min_level: 2
  max_level: 6


## => Markdown Enhancements
## Mathjax
mathjax: true # false (default), true
mathjax_autoNumber: true # false (default), true

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath


## Mermaid
mermaid: true # false (default), true

## Chart
chart: true # false (default), true


  
# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "team"
    values:
      layout:       "profile"

collections:
  team:
    output: true
    permalink: /team/:title


# -----------------------------------------------------------------------------
# 统计
# -----------------------------------------------------------------------------




# -----------------------------------------------------------------------------
# bib
# -----------------------------------------------------------------------------
scholar:
  style: apa
  locale: en
  first: Edmund Y.
  last: Lam

  sort_by: none
  order: descending

  # group_by: year
  # group_order: descending

  source: ./_bibliography
  bibliography: journal
  bibliography_template: bib
  slug_field: 'key'

  replace_strings: true
  join_strings:    true

  query: "@*"

## => Plugins
##############################
# remote_theme: isl-hku/jekyll-theme-neysa
plugins_dir: _plugins
plugins:
  # - jekyll-feed
  # - jekyll-paginate
  # - jekyll-sitemap
  - jemoji
  - jekyll-scholar
  - jekyll-email-protect
  # - jekyll-gist
  - jekyll-toc
  - jekyll-twitter-plugin
  # - jekyll-remote-theme # add this line to the plugins list if you already have one






github: [metadata]

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------
academicons:
  version: "1.9.0"
  integrity: "sha512-W4yqoT1+8NLkinBLBZko+dFB2ZbHsYLDdr50VElllRcNt2Q4/GSs6u71UHKxB7S6JEMCp5Ve4xjh3eGQl/HRvg=="
bootstrap:
  version: "4.5.2"
  integrity:
    css: "sha512-MoRNloxbStBcD8z3M/2BmnT+rg4IsMxPkXaGh2zD6LGNNFE80W3onsAhRcMAMrSoyWL9xD7Ert0men7vR8LUZg=="
    js: "sha512-M5KW3ztuIICmVIhjSqXe01oV2bpe248gOxqmlcYrEzAvws7Pw3z6BK0iGbrwvdrUQUhi3eXgtxp5I8PDo9YfjQ=="
fontawesome:
  version: "5.14.0"
  integrity: "sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
jquery:
  version: "3.5.1"
  integrity: "sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
mathjax:
  version: "3.1.2"
mansory:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.19.1"
  integrity:
    css: "sha512-RO38pBRxYH3SoOprtPTD86JFOclM51/XTIdEPh5j8sj4tp8jmQIx26twG52UaLi//hQldfrh7e51WzP9wuP32Q=="
    js: "sha512-Mug9KHKmroQFMLm93zGrjhibM2z2Obg9l6qFG2qKjXEXkMp/VDkI4uju9m4QKPjWSwQ6O2qzZEnJDEeCw0Blcw=="
popper:
  version: "2.4.4"
  integrity: "sha512-eUQ9hGdLjBjY3F41CScH3UX+4JDSI9zXeroz7hJ+RteoCaY+GP/LDoM8AO+Pt+DRFw3nXqsjh9Zsts8hnYv8/A=="
