source 'https://rubygems.org'

gem 'jekyll', '~> 4.3'
gem 'jekyll-feed', '~> 0.17'  
gem 'jekyll-paginate-v2'  
gem 'jekyll-scholar', github: 'inukshuk/jekyll-scholar', branch: 'main'  
gem 'jekyll-email-protect'
gem 'coderay', '~> 1.1.0'
gem 'jemoji'
gem 'unicode_utils'
gem 'jekyll-toc'
gem 'font-awesome-less'
gem 'liquid', '~> 4.0'
gem 'jekyll-twitter-plugin'